CREATE TABLE [dbo].[axf_Interfaces](
	[InterfaceId] [varchar](80) NOT NULL,
	[LastExecutionDate] [datetime] NULL,
 CONSTRAINT [PK_axf_Interfaces] PRIMARY KEY CLUSTERED 
(
	[InterfaceId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]