//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace AxonifyIntegration.Data.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class API_Subject
    {
        [Required]
        [StringLength(128)]
        public string subjectExternalId { get; set; }

        [Required]
        [StringLength(128)]
        public string categoryExternalId { get; set; }

        [Required]
        [StringLength(60)]
        public string subjectName { get; set; }

        [StringLength(128)]
        public string revision { get; set; }
    }
}
