//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonifyIntegration.Data.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class API_UserBehavior
    {
        public int userBehaviorId { get; set; }
        public string observerEmployeeId { get; set; }
        public string observeeEmployeeId { get; set; }
        public Nullable<System.DateTime> observationDateTime { get; set; }
        public string behaviorCode { get; set; }
        public Nullable<int> positiveObservations { get; set; }
        public Nullable<int> negativeObservations { get; set; }
        public string comment { get; set; }
    }
}
