//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonifyIntegration.Data.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class API_User
    {
        public string employeeId { get; set; }
        public Nullable<bool> active { get; set; }
        public string fullName { get; set; }
        public string nickName { get; set; }
        public string Username { get; set; }
        public string md5Password { get; set; }
        public Nullable<int> userTypeId { get; set; }
        public string Email { get; set; }
        public Nullable<int> languageId { get; set; }
        public Nullable<System.DateTime> hireDate { get; set; }
        public string jobTitle { get; set; }
        public string department { get; set; }
        public string team { get; set; }
        public string lineOfBusiness { get; set; }
        public Nullable<int> areasOfInterestId { get; set; }
        public Nullable<bool> suspended { get; set; }
    }
}
