//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonifyIntegration.Data.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class API_UserTimeSpent
    {
        public int userTimeSpentId { get; set; }
        public string employeeId { get; set; }
        public Nullable<int> totalTime { get; set; }
        public Nullable<int> dailyTrainingTime { get; set; }
        public Nullable<int> introductoryTrainingTime { get; set; }
        public Nullable<int> certificationTrainingTime { get; set; }
        public Nullable<int> refresherTrainingTime { get; set; }
        public Nullable<int> extraQuestionTrainingTime { get; set; }
        public Nullable<int> extraTrainingModueTime { get; set; }
        public Nullable<int> gamePlayTime { get; set; }
    }
}
