//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonifyIntegration.Data.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class API_KnowledgeMap
    {
        public int knowledgeMapId { get; set; }
        public string employeeId { get; set; }
        public string categoryExternalId { get; set; }
        public string subjectExternalId { get; set; }
        public string topicExternalId { get; set; }
        public Nullable<int> learnerStatusId { get; set; }
        public Nullable<int> certificationStatusId { get; set; }
        public Nullable<int> introductoryStatusId { get; set; }
        public Nullable<int> trainingModuleCompletedId { get; set; }
        public Nullable<System.DateTime> trainingModuleLastCompletionTimestamp { get; set; }
        public Nullable<System.DateTime> topicGraduationTimestamp { get; set; }
    }
}
