//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonifyIntegration.Data.DataModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using Newtonsoft.Json;
    using Object.Helpers;

    public partial class API_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public API_User()
        {
            this.API_UserAreasOfInterest = new HashSet<API_UserAreasOfInterest>();
            this.areasOfInterest = new List<string>();
        }

        public string employeeId { get; set; }
        public bool active { get; set; }
        public string fullName { get; set; }
        public string nickName { get; set; }
        public string userName { get; set; }
        public string md5Password { get; set; }
        public string userType { get; set; }
        public string email { get; set; }
        public string language { get; set; }
        
        public System.DateTime hireDate { get; set; }

        public string jobTitle { get; set; }
        public string department { get; set; }
        public string team { get; set; }
        public string lineOfBusiness { get; set; }
        public bool suspended { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<API_UserAreasOfInterest> API_UserAreasOfInterest { get; set; }
        
        
        [NotMapped]
        public List<string> areasOfInterest { get; set; }
    }
}
