//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxonifyIntegration.Data.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class API_CertificationCompletion
    {
        public string employeeId { get; set; }
        public string categoryExternalId { get; set; }
        public string subjectExternalId { get; set; }
        public string topicExternalId { get; set; }
        public Nullable<System.DateTime> completionTimestamp { get; set; }
        public Nullable<decimal> assessmentScore { get; set; }
        public Nullable<int> timeSpent { get; set; }
    }
}
